### ISSUE TITLE
docker: command not found

### ISSUE THREAD

**Issue by half2me** [usimd/pi-gen-action#112]
**Describe the bug**
As part of my build process I need to use docker commands. When I try to use `docker` or `/usr/bin/docker` its not available. I explicitly install it in a previous step as part of my github action, and it works fine everywhere except in `00-run.sh` scripts.

**To Reproduce**
```
- run: curl -fsSL https://get.docker.com | sh
- uses: usimd/pi-gen-action@v1
   id: build
   with:
     pi-gen-dir: pi-gen
     pi-gen-version: arm64
     export-last-stage-only: true
     stage-list: clean-stage stage0 stage1 stage2 ./my-stage
     github-token: ${{ github.token }}
     image-name: foo
```

My custom stage has this in `00-run.sh`
```bash
#!/bin/bash -e

on_chroot << EOF
    curl -fsSL https://get.docker.com | sh
    usermod -aG docker ${FIRST_USER_NAME}
EOF

docker info # <- this line works fine in pi-gen, but fails in the action
```

**Expected behavior**
docker should be available to use

**Logs**
```
./00-run.sh: line 20: docker: command not found
```

**Additional context**
