### ISSUE TITLE
Add example for exporting multiple image stages

### ISSUE THREAD

**Issue by Mearman** [usimd/pi-gen-action#123]
Thank you for such a helpful action!

I'm building an image that just adds one main package (and its dependencies) and then the package's config, as well as updating `/boot/firmware/config.txt`.

I would like to export the `Lite` and `Full` images, but I'm not sure what the best approach is without repeating the whole job.

Is there a better way to do it than something like the following:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: usimd/pi-gen-action@v1
        id: base
        with:
          stage-list: stage0 stage1 ./custom-stage

    - uses: usimd/pi-gen-action@v1
        id: stage2
        with:
          stage-list: stage2
              - uses: usimd/pi-gen-action@v1

    - uses: actions/upload-artifact@v4
      with:
        name: lite-image
        path: ${{ steps.stage2.outputs.image-path }}

    - uses: usimd/pi-gen-action@v1
        id: stage3
        with:
          stage-list: stage3

    - uses: actions/upload-artifact@v4
      with:
        name: full-image
        path: ${{ steps.stage3.outputs.image-path }}
```
