### ISSUE TITLE
tee: /pi-gen/work/<repo>/build.log: No such file or directory

### ISSUE THREAD

**Issue by abevoelker** [usimd/pi-gen-action#23]
Thanks for the GitHub Action - this is very handy. But every time I run it on [abevoelker/pi-scan](https://github.com/abevoelker/pi-scan) I seem to be getting this error:

**Describe the bug**
```
Error: pi-gen build failed with exit code 1
tee: /pi-gen/work/pi-scan/build.log: No such file or directory
```

**To Reproduce**
- Run the build action on my https://github.com/abevoelker/pi-scan repo

This is my GitHub Action config:

```yaml
name: Build Pi Scan image
on: workflow_dispatch

jobs:
  build_image:
    strategy:
      matrix:
        build_input: [mouse, touch]
        build_arch: [arm32, arm64]
    name: Build Pi Scan image
    runs-on: ubuntu-latest
    env:
      BUILD_INPUT: ${{ matrix.build_input }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          cp -a "config/${BUILD_INPUT}.ini" "build-image/stage-piscan/04-install-setup/files/config.ini"
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          disable-first-boot-user-rename: 1
          export-last-stage-only: true
          hostname: raspberrypi
          image-name: 'pi-scan'
          keyboard-keymap: us
          keyboard-layout: English (US)
          locale: en_US.UTF-8
          timezone: America/Chicago
          password: ' '
          stage-list: stage0 stage1 stage2 ./build-image/stage-piscan
          pi-gen-version: ${{ matrix.build_arch == 'arm32' && 'master' || 'arm64' }}
          # these two options are just for debugging the GitHub Action failure:
          verbose-output: true
          pi-gen-dir: ${{ github.workspace }}/pi-gennnn
      - uses: actions/upload-artifact@v3
        with:
          name: pi-scan-${{ matrix.build_input }}-${{ matrix.build_arch }}
          path: ${{ steps.build.outputs.image-path }}
```

I've tried disabling `verbose-output` as well as setting `pi-gen-dir` to a different directory, but it still seems to error out with the same path error referencing `/pi-gen/work/pi-scan/build.log`

**Expected behavior**
Build runs to completion

**Logs**
```
...
  Setting up libperl5.32:amd64 (5.32.1-4+deb11u2) ...
  Setting up gpgconf (2.2.27-2+deb11u2) ...
  Setting up libcurl4:amd64 (7.74.0-1.3+deb11u3) ...
  Setting up curl (7.74.0-1.3+deb11u3) ...
  Setting up qemu-utils (1:5.2+dfsg-11+deb11u2) ...
  Setting up gpg (2.2.27-2+deb11u2) ...
  Setting up rsync (3.2.3-4+deb11u1) ...
  invoke-rc.d: could not determine current runlevel
  invoke-rc.d: policy-rc.d denied execution of start.
  Setting up libarchive-tools (3.4.3-2+deb11u1) ...
  Setting up perl (5.32.1-4+deb11u2) ...
  Setting up quilt (0.66-2.1) ...
  Setting up liberror-perl (0.17029-1) ...
  Setting up git (1:2.30.2-1) ...
  Setting up libdevmapper1.02.1:amd64 (2:1.02.175-2.1) ...
  Setting up libparted2:amd64 (3.4-1) ...
  Setting up dmsetup (2:1.02.175-2.1) ...
  Setting up kpartx (0.8.5-2) ...
  Setting up parted (3.4-1) ...
  Processing triggers for libc-bin (2.31-13+deb11u4) ...
  Processing triggers for ca-certificates (20210119) ...
  Updating certificates in /etc/ssl/certs...
  0 added, 0 removed; done.
  Running hooks in /etc/ca-certificates/update.d...
  done.
  Removing intermediate container 58d8d6a8ae38
   ---> 7c3085149188
  Step 5/6 : COPY . /pi-gen/
   ---> 6bd157955697
  Step 6/6 : VOLUME [ "/pi-gen/work", "/pi-gen/deploy"]
   ---> Running in b3b8368661d0
  Removing intermediate container b3b8368661d0
   ---> c4fa810dceda
  Successfully built c4fa810dceda
  Successfully tagged pi-gen:latest
  To disable user rename on first boot, FIRST_USER_PASS needs to be set
  Not setting FIRST_USER_PASS makes your system vulnerable and open to cyberattacks
  Warning: tee: /pi-gen/work/pi-scan/build.log: No such file or directory
  [18:50:57] Unloading image
  Warning: real	0m0.600s
  Warning: user	0m0.034s
  Warning: sys	0m0.006s
Error: pi-gen build failed with exit code 1
tee: /pi-gen/work/pi-scan/build.log: No such file or directory

real	0m0.600s
user	0m0.034s
sys	0m0.006s
```

**Additional context**
N/A

Any idea what I'm doing wrong?
