### ISSUE TITLE
bookworm not working?

### ISSUE THREAD

**Issue by builderjer** [usimd/pi-gen-action#78]
I am trying to upgrade an image using `bookworm` instead of `bullseye`

**To Reproduce**
- workflow configuration
- action configuration of failed job
- used action runner

### workflow config
```
name: Build raspbian-ovos
on:
  workflow_dispatch:

jobs:
  pi-gen-ovos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: usimd/pi-gen-action@v1.6.0
        id: build
        with:
          # Final image name.
          image-name: raspbian-ovos-dev

          # List of stage name to execute in given order. Relative and absolute paths to
          # custom stage directories are allowed here. Note that by default pi-gen exports
          # images in stage2 (lite), stage4 and stage5. You probably want to hook in custom
          # stages before one of the exported stages. Otherwise, the action will make sure
          # any custom stage will include an image export directive.
          stage-list: stage0 stage1 stage2 ./stage-prep ./stage-core ./stage-phal ./stage-audio ./stage-skills ./stage-hivemind ./stage-finalize

          # Host name of the image.
          hostname: raspOvos

          # Default keyboard keymap.
          keyboard-keymap: us

          # Default keyboard layout.
          keyboard-layout: English (US)

          # Default locale of the system image.
          locale: en_US.UTF-8

          # Default wifi country
          wpa-country: US

          # Default timezone
          timezone: America/Denver

          # Name of the initial user account.
          username: ovos

          # Password of the intial user account, locked if empty.
          password: 'ovos'

          # Compression to apply on final image (either "none", "zip", "xz" or "gz").
          compression: zip

          # Compression level to be used. From 0 to 9 (refer to the tool man page for more
          # information on this. Usually 0 is no compression but very fast, up to 9 with the
          # best compression but very slow).
          compression-level: 6

          # Disable the renaming of the first user during the first boot. This make it so
          # 'username' stays activated. 'username' must be set for this to work. Please be
          # aware of the implied security risk of defining a default username and password
          # for your devices.
          disable-first-boot-user-rename: 1

          # Additional options to include in PIGEN_DOCKER_OPTS
          docker-opts: ''

          # Set whether a NOOBS image should be built as well. If enabled, the output
          # directory containing the NOOBS files will be saved as output variable
          # 'image-noobs-path'.
          enable-noobs: false

          # Enable SSH access to Pi.
          enable-ssh: 1

          # If this feature is enabled, the action will configure pi-gen to not export any
          # stage as image but the last one defined in property 'stage-list'. This is
          # helpful when building a single image flavor (in contrast to building a
          # lite/server and full-blown desktop image), since it speeds up the build process
          # significantly.
          export-last-stage-only: true

          # Comma or whitespace separated list of additional packages to install on host
          # before running pi-gen. Use this list to add any packages your custom stages may
          # require. Note that this is not affecting the final image. In order to add
          # additional packages, you need to add a respective 'XX-packages' file in your
          # custom stage.
          extra-host-dependencies: ''

          # Comma or whitespace separated list of additional modules to load on host before
          # running pi-gen. If your custom stage requires additional software or kernel
          # modules to be loaded, add them here. Note that this is not meant to configure
          # modules to be loaded in the target image.
          extra-host-modules: ''

          # Token to use for checking out pi-gen repo.
          github-token: ${{ github.token }}

          # Path where selected pi-gen ref will be checked out to. If the path does not yet
          # exist, it will be created (including its parents).
          pi-gen-dir: pi-gen

          # GitHub repository to fetch pi-gen from, must be a fork from RPi-Distro/pi-gen.

          pi-gen-repository: RPi-Distro/pi-gen

          # Release version of pi-gen to use. This can both be a branch or tag name known in
          # the pi-gen repository.
          pi-gen-version: arm64

          # The release version to build images against. Valid values are jessie, stretch,
          # buster, bullseye, and testing.
          release: bookworm

          # Setting to `1` will prevent pi-gen from dropping the "capabilities" feature.
          # Generating the root filesystem with capabilities enabled and running it from a
          # filesystem that does not support capabilities (like NFS) can cause issues. Only
          # enable this if you understand what it is.
          setfcap: ''

          # Use qcow2 images to reduce space and runtime requirements.
          use-qcow2: 1

          # Print all output from pi-gen.
          verbose-output: true

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ovosimages.ziggyai.online
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "${{ steps.build.outputs.image-path }}"
          target: "raspbian/development"
          strip_components: 4
```

### error
```

Run usimd/pi-gen-action@v1.6.0
  with:
    image-name: raspbian-ovos-dev
    stage-list: stage0 stage1 stage2 ./stage-prep ./stage-core ./stage-phal ./stage-audio ./stage-skills ./stage-hivemind ./stage-finalize
    hostname: raspOvos
    keyboard-keymap: us
    keyboard-layout: English (US)
    locale: en_US.UTF-8
    wpa-country: US
    timezone: America/Denver
    username: ovos
    password: ovos
    compression: zip
    compression-level: 6
    disable-first-boot-user-rename: 1
    enable-noobs: false
    enable-ssh: 1
    export-last-stage-only: true
    github-token: ***
    pi-gen-dir: pi-gen
    pi-gen-repository: RPi-Distro/pi-gen
    pi-gen-version: arm64
    release: bookworm
    use-qcow2: 1
    verbose-output: true
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Validating input and generating pi-gen config
Error: release must be one of ["bullseye", "jessie", "stretch", "buster", "testing"]
```

**Expected behavior**

**Logs**
If possible, share (verbose/debug) logs of your failed workflow job.

**Additional context**

**Comment by builderjer** [comment]
Not sure why this is happening, but I still cant get a build with `bookworm`
```
Run usimd/pi-gen-action@v1.6.0
  with:
    image-name: raspOVOS-dev
    stage-list: stage0 stage1 stage2 ./stage-prep ./stage-core ./stage-phal ./stage-audio ./stage-skills ./stage-hivemind ./stage-finalize
    hostname: raspOvos
    keyboard-keymap: us
    keyboard-layout: English (US)
    locale: en_US.UTF-8
    wpa-country: US
    timezone: America/Denver
    username: ovos
    password: ovos
    compression: zip
    compression-level: 6
    disable-first-boot-user-rename: 1
    enable-noobs: false
    enable-ssh: 1
    export-last-stage-only: true
    github-token: ***
    pi-gen-dir: pi-gen
    pi-gen-repository: RPi-Distro/pi-gen
    pi-gen-version: arm64
    release: bookworm
    use-qcow2: 1
    verbose-output: true
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Validating input and generating pi-gen config
Error: release must be one of ["bullseye", "jessie", "stretch", "buster", "testing"]
```

**Comment by usimd** [comment]
Sorry to respond so late and thanks for reporting this.

Although I did update the code,  I did not yet create a release and update `v1` tag. If you specify `master` as revision to check out in your workflow, it should be working.

I'll try to find the time to release a new version asap.

**Comment by builderjer** [comment]
I am still getting this
```
Run usimd/pi-gen-action@master
  with:
    image-name: raspOVOS-dev
    stage-list: stage0 stage1 stage2 ./stage-prep ./stage-core ./stage-phal ./stage-audio ./stage-skills ./stage-hivemind ./stage-finalize
    hostname: raspOvos
    keyboard-keymap: us
    keyboard-layout: English (US)
    locale: en_US.UTF-8
    wpa-country: US
    timezone: America/Denver
    username: ovos
    password: ovos
    compression: zip
    compression-level: 6
    disable-first-boot-user-rename: 1
    enable-noobs: false
    enable-ssh: 1
    export-last-stage-only: true
    github-token: ***
    pi-gen-dir: pi-gen
    pi-gen-repository: RPi-Distro/pi-gen
    pi-gen-version: arm64
    release: bookworm
    use-qcow2: 1
    verbose-output: true
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Validating input and generating pi-gen config
Error: release must be one of ["bullseye", "jessie", "stretch", "buster", "testing"]
```

**Comment by usimd** [comment]
Sorry about the troubles, I did not do the update of the compiled action code right after adding this. I wanted to do some more cleanups and lost track of time :smile: 

Anyways, this should now work (latest `v1` points to `v1.7.0` including this fix). Let me know if there are still errors.

**Comment by builderjer** [comment]
Thanks for your work!!  This is working as expected now.

**Comment by builderjer** [comment]
I hate to reopen this, but I think it is still trying to use the `bullseye` files

```

Running pi-gen build
  Warning: #0 building with "default" instance using docker driver
  Warning: #1 [internal] load build definition from Dockerfile
  Warning: #1 transferring dockerfile: 560B done
  Warning: #1 DONE 0.0s
  Warning: #2 [internal] load .dockerignore
  Warning: #2 transferring context: 92B done
  Warning: #2 DONE 0.0s
  Warning: #3 [internal] load metadata for docker.io/library/debian:bullseye
  Warning: #3 ...
  Warning: #4 [auth] library/debian:pull token for registry-1.docker.io
  Warning: #4 DONE 0.0s
  Warning: #3 [internal] load metadata for docker.io/library/debian:bullseye
```

and my workflow file
```
name: Build raspOVOS-gui
on:
  workflow_dispatch:

jobs:
  pi-gen-ovos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          # Final image name.
          image-name: raspOVOS-gui-dev

          # List of stage name to execute in given order. Relative and absolute paths to
          # custom stage directories are allowed here. Note that by default pi-gen exports
          # images in stage2 (lite), stage4 and stage5. You probably want to hook in custom
          # stages before one of the exported stages. Otherwise, the action will make sure
          # any custom stage will include an image export directive.
          stage-list: stage0 stage1 stage2 ./stage-prep ./stage-core ./stage-phal ./stage-audio ./stage-skills ./stage-hivemind ./stage-ggwave ./stage-gui ./stage-finalize

          # Host name of the image.
          hostname: raspOvos

          # Default keyboard keymap.
          keyboard-keymap: us

          # Default keyboard layout.
          keyboard-layout: English (US)

          # Default locale of the system image.
          locale: en_US.UTF-8

          # Default wifi country
          wpa-country: US

          # Default timezone
          timezone: America/Denver

          # Name of the initial user account.
          username: ovos

          # Password of the intial user account, locked if empty.
          password: 'ovos'

          # Compression to apply on final image (either "none", "zip", "xz" or "gz").
          compression: zip

          # Compression level to be used. From 0 to 9 (refer to the tool man page for more
          # information on this. Usually 0 is no compression but very fast, up to 9 with the
          # best compression but very slow).
          compression-level: 6

          # Disable the renaming of the first user during the first boot. This make it so
          # 'username' stays activated. 'username' must be set for this to work. Please be
          # aware of the implied security risk of defining a default username and password
          # for your devices.
          disable-first-boot-user-rename: 1

          # Additional options to include in PIGEN_DOCKER_OPTS
          docker-opts: ''

          # Set whether a NOOBS image should be built as well. If enabled, the output
          # directory containing the NOOBS files will be saved as output variable
          # 'image-noobs-path'.
          enable-noobs: false

          # Enable SSH access to Pi.
          enable-ssh: 1

          # If this feature is enabled, the action will configure pi-gen to not export any
          # stage as image but the last one defined in property 'stage-list'. This is
          # helpful when building a single image flavor (in contrast to building a
          # lite/server and full-blown desktop image), since it speeds up the build process
          # significantly.
          export-last-stage-only: true

          # Comma or whitespace separated list of additional packages to install on host
          # before running pi-gen. Use this list to add any packages your custom stages may
          # require. Note that this is not affecting the final image. In order to add
          # additional packages, you need to add a respective 'XX-packages' file in your
          # custom stage.
          extra-host-dependencies: ''

          # Comma or whitespace separated list of additional modules to load on host before
          # running pi-gen. If your custom stage requires additional software or kernel
          # modules to be loaded, add them here. Note that this is not meant to configure
          # modules to be loaded in the target image.
          extra-host-modules: ''

          # Token to use for checking out pi-gen repo.
          github-token: ${{ github.token }}

          # Path where selected pi-gen ref will be checked out to. If the path does not yet
          # exist, it will be created (including its parents).
          pi-gen-dir: pi-gen

          # GitHub repository to fetch pi-gen from, must be a fork from RPi-Distro/pi-gen.

          pi-gen-repository: RPi-Distro/pi-gen

          # Release version of pi-gen to use. This can both be a branch or tag name known in
          # the pi-gen repository.
          pi-gen-version: arm64

          # The release version to build images against. Valid values are jessie, stretch,
          # buster, bullseye, and testing.
          release: bookworm

          # Setting to `1` will prevent pi-gen from dropping the "capabilities" feature.
          # Generating the root filesystem with capabilities enabled and running it from a
          # filesystem that does not support capabilities (like NFS) can cause issues. Only
          # enable this if you understand what it is.
          setfcap: ''

          # Use qcow2 images to reduce space and runtime requirements.
          use-qcow2: 1

          # Print all output from pi-gen.
          verbose-output: true

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ovosimages.ziggyai.online
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "${{ steps.build.outputs.image-path }}"
          target: "raspbian/development"
          strip_components: 4
```
